### ISSUE TITLE
How do I use my own OTP broker?

### ISSUE THREAD

**Issue by iamroi** [alhaji-aki/laravel-otp-token#14]
Thanks for the great package!

I would like to use the same OTP when the user tries to resend the OTP. Currently the package, deletes existing OTP and then creates a new one.

I have tried to override the `OtpTokenBroker` class but not able to get it work.

Could you please help guide me on this? Thanks

**Comment by alhaji-aki** [comment]
Sorry for the late response. There is currently no way of directly overriding the `OtpTokenBroker` class. But you can override the `OtpTokenBrokerManager` class specifically the `resolve` since that is where the class is instantiated.

After overriding the manager class you can register the class in the register method of your service provider like so 

```php
$this->app->singleton('auth.otp_token', function (Application $app) {
    return new YourOtpTokenBrokerManager($app);
});
```

I hope this helps.

**Comment by iamroi** [comment]
Awesome thanks! That seems to be a great option to override 🙌
